### ISSUE TITLE
Support for flaky tests

### ISSUE THREAD

**Issue by taman9333** [ctrf-io/go-ctrf-json-reporter#12]
I have integrated [GitHub Test Reporter](https://github.com/ctrf-io/github-test-reporter) into my GitHub CI. My application is written in Golang, and it has some flaky tests. I added the following job to detect flaky tests:

```
- name: Post PR Comment
  run: npx github-actions-ctrf flaky ctrf-report.json --pull-request
  if: always()
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

However, I keep getting the following result:
```
No flaky tests detected. ✨
```

I suspect that the `flaky` flag might not be supported. Am I wrong?
